### ISSUE TITLE
Can I draw a QWidget on VkWindow?

### ISSUE THREAD

**Issue by JavinYang** [ikryukov/QtVulkan#2]
```
MainWindow::MainWindow(QWidget* parent) : QMainWindow(parent), ui(new Ui::MainWindow) {
    ui->setupUi(this);
    VkWindow* vkWin = new VkWindow();
    QWidget* vkWidget = QWidget::createWindowContainer(vkWin);
    QWidget* T_T = new QWidget(vkWidget);
    T_T->resize(100, 100);
    ui->renderLayout->addWidget(vkWidget);
}
```
Obviously, T_T does not display.
what i should do?

**Comment by ikryukov** [comment]
Seems that you need to add T_T to renderLayout?

**Comment by JavinYang** [comment]
I want T_T to be overlaid on the vkWidget. If 
```
ui->renderLayout->addWidget(vkWidget);
ui->renderLayout->addWidget(T_T);
```
 then left side is vkWidget right side is T_T.

**Comment by JavinYang** [comment]
> Seems that you need to add T_T to renderLayout?

I want T_T to be overlaid on the vkWidget. If
```
ui->renderLayout->addWidget(vkWidget);
ui->renderLayout->addWidget(T_T);
```
then left side is vkWidget right side is T_T.

**Comment by ikryukov** [comment]
I think this might help you: http://blog.qt.io/blog/2018/05/30/vulkan-for-qt-on-macos/
